
USE PartyDJ;
GO

IF OBJECT_ID('dbo.Artists', 'U') IS NULL
BEGIN
  CREATE TABLE Artists (
    ArtistID BIGINT NOT NULL IDENTITY(1,1),
    ArtistName NVARCHAR(255) NOT NULL,
    SpotifyArtistID NVARCHAR(64) NULL CONSTRAINT UQ_Artists_SpotifyArtistID UNIQUE,
    CreatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_Artists_CreatedAt DEFAULT SYSUTCDATETIME()
    CONSTRAINT PK_Artists PRIMARY KEY
  );
END;
GO