USE PartyDJ;
GO

IF OBJECT_ID('dbo.Votes', 'U') IS NULL
BEGIN
  CREATE TABLE Votes (
    VoteID BIGINT NOT NULL IDENTITY(1,1) CONSTRAINT PK_Votes PRIMARY KEY,
    QueueItemID BIGINT NOT NULL CONSTRAINT FK_Votes_QueueItems_QueueItemID REFERENCES QueueItems(QueueItemID),
    UserID BIGINT NOT NULL CONSTRAINT FK_Votes_Users_UserID REFERENCES Users(UserID),
    VoteType NVARCHAR(16) NOT NULL,
    VoteValue SMALLINT NOT NULL,
    CreatedAt DATETIME2(3) NOT NULL CONSTRAINT DF_Votes_CreatedAt DEFAULT SYSUTCDATETIME(),
    CONSTRAINT UQ_Votes_QueueItemID_UserID UNIQUE (QueueItemID, UserID)
  );
END;
GO